general:
  path: configs/config.yaml
log:
  path: logs/log.json
  minseverity: debug
  maxage: 10
  maxsize: 10
  maxfiles: 10
Audit:
  path: logs/audit.json
  minSeverity: info
  maxAge: 30
  maxSize: 10
  maxFiles: 11
WebServer:
  port: 443
  listenAddress: 0.0.0.0
  sslIsEnable: false
  sslCertPath: configs/ssl/cert.pem
  sslKeyPath: configs/ssl/key.pem
  sesionTimeout: 999
  username: admin
  password: Password
Configs:
- name: PROD
  path: configs/segment-config-example.yaml