General:
    confCheckInterval: 1

Sync:
    isEnable: true
    token: fvdknlvd9ergtuklroegkvnemc90ru34fcemf340[ij

Prometheus:
    url: http://prometheus:8428/api/v1/write
    auth: false
    username: user
    password: password
    metricName: dns_resolve
    retriesCount: 2
    buferSize: 2
    labels:
        opcode: false
        authoritative: false
        truncated: true
        rcode: true
        recursionDesired: false
        recursionAvailable: false
        authenticatedData: false
        checkingDisabled: false
        pollingRate: false
        recursion: true

Resolvers:
  path: config/prod_srv_cs_srv.csv
  delimeter: ','
  extraDelimeter: '&'
  pullTimeout: 3